import { useEffect, useState } from 'react';
import { Navigate, Route, Routes, useNavigate } from 'react-router-dom';
import api from './services/api';
import { useAuth } from './context/AuthContext';
import CustomerDashboard from './CustomerDashboard';
import PaymentSuccessPage from './PaymentSuccessPage';
import PaymentCancelPage from './PaymentCancelPage';
import BookingConfirmationPage from './BookingConfirmationPage';
import './App.css';

const resources = {
  customers: { title: 'Customers', path: '/customers', fields: [['full_name', 'Full name'], ['email', 'Email', 'email'], ['phone', 'Phone'], ['address', 'Address'], ['password', 'Account password', 'password']] },
  vehicles: { title: 'Vehicles', path: '/vehicles', fields: [['customer_id', 'Customer', 'select', 'customers'], ['registration_number', 'Registration number'], ['make', 'Make'], ['model', 'Model'], ['manufacture_year', 'Manufacture year', 'number']] },
  services: { title: 'Services', path: '/services', fields: [['service_name', 'Service name'], ['description', 'Description'], ['price', 'Price', 'number'], ['estimated_duration_minutes', 'Duration (minutes)', 'number']] },
  mechanics: { title: 'Mechanics', path: '/mechanics', fields: [['full_name', 'Full name'], ['email', 'Email', 'email'], ['phone', 'Phone'], ['specialization', 'Specialization'], ['password', 'Login password', 'password']] },
  'spare-parts': { title: 'Spare parts', path: '/spare-parts', fields: [['part_name', 'Part name'], ['stock_quantity', 'Stock quantity', 'number'], ['unit_price', 'Unit price', 'number']] },
  bookings: { title: 'Bookings', path: '/bookings', fields: [['customer_id', 'Customer', 'select', 'customers'], ['vehicle_id', 'Vehicle', 'select', 'vehicles'], ['service_type_id', 'Service', 'select', 'services'], ['preferred_date', 'Preferred date', 'date'], ['customer_notes', 'Notes']] },
  invoices: { title: 'Invoices', path: '/invoices', fields: [['booking_id', 'Booking', 'select', 'bookings']] },
  payments: { title: 'Payments', path: '/payments', fields: [['invoice_id', 'Invoice', 'select', 'invoices'], ['payment_amount', 'Amount', 'number'], ['payment_method', 'Method'], ['payment_status', 'Status']] },
};

function errorMessage(error) {
  if (!error.response) return 'Unable to connect to the Laravel server.';
  if (error.response.status === 401) return 'Your session has expired. Please sign in again.';
  if (error.response.status === 403) return 'You are not authorized to perform this action.';
  if (error.response.status === 404) return 'The requested record was not found.';
  if (error.response.status === 422) return Object.values(error.response.data?.errors || {}).flat().join(' ') || error.response.data?.message || 'Please correct the form.';
  if (error.response.status >= 500) return 'Laravel returned a server error. Check the application logs.';
  return error.response.data?.message || 'The operation failed.';
}

function Modal({ title, fields, values, setValues, options, onSubmit, onClose, saving, error }) {
  return <div className="modal-backdrop"><div className="modal card"><div className="section-heading"><h3>{title}</h3><button type="button" className="btn btn-outline" onClick={onClose}>Cancel</button></div>{error && <div className="alert error">{error}</div>}<form className="stack-form" onSubmit={onSubmit}>{fields.map(([name, label, type = 'text', source]) => <label key={name}>{label}{type === 'select' ? <select required value={values[name] || ''} onChange={(event) => setValues({ ...values, [name]: event.target.value })}><option value="">Select {label.toLowerCase()}</option>{(options[source] || []).map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select> : <input required={!['description', 'phone', 'address', 'password', 'manufacture_year', 'estimated_duration_minutes', 'customer_notes'].includes(name)} type={type} min={type === 'number' ? 0 : undefined} value={values[name] ?? ''} onChange={(event) => setValues({ ...values, [name]: event.target.value })} />}</label>)}<button disabled={saving} className="btn btn-primary" type="submit">{saving ? 'Saving...' : 'Save'}</button></form></div></div>;
}

function useOptions(sourceNames) {
  const [options, setOptions] = useState({});
  const sourceKey = sourceNames.join('|');
  useEffect(() => { Promise.all(sourceKey.split('|').filter(Boolean).map(async (source) => { const response = await api.get(resources[source]?.path || `/${source}`); return [source, response.data?.data || []]; })).then((entries) => { const next = {}; entries.forEach(([source, data]) => { next[source] = data.map((item) => ({ value: item.customer_id || item.vehicle_id || item.service_type_id || item.booking_id || item.invoice_id || item.mechanic_id, label: item.full_name || item.registration_number || item.service_name || `Booking #${item.booking_id}` })); }); setOptions(next); }).catch(() => setOptions({})); }, [sourceKey]);
  return options;
}

function ResourcePage({ resourceKey, role }) {
  const config = resources[resourceKey];
  const idKey = config.primaryKey || ({ customers: 'customer_id', vehicles: 'vehicle_id', services: 'service_type_id', mechanics: 'mechanic_id', 'spare-parts': 'part_id', bookings: 'booking_id', invoices: 'invoice_id', payments: 'payment_id' }[resourceKey]);
  const visibleFields = config.fields.filter((field) => !(role === 'customer' && field[0] === 'customer_id'));
  const [items, setItems] = useState([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [search, setSearch] = useState(''); const [query, setQuery] = useState(''); const [modal, setModal] = useState(null); const [error, setError] = useState('');
  const sourceNames = [...new Set([...visibleFields.map((field) => field[3]), ...(resourceKey === 'bookings' && role === 'admin' ? ['mechanics'] : [])].filter(Boolean))]; const options = useOptions(sourceNames);
  const load = () => { setLoading(true); api.get(config.path, { params: query ? { search: query } : {} }).then((response) => setItems(response.data?.data || [])).catch((requestError) => setError(errorMessage(requestError))).finally(() => setLoading(false)); };
  useEffect(() => { api.get(config.path, { params: query ? { search: query } : {} }).then((response) => setItems(response.data?.data || [])).catch((requestError) => setError(errorMessage(requestError))).finally(() => setLoading(false)); }, [config.path, query]);
  const openCreate = () => { setError(''); setModal({}); };
  const openEdit = (item) => { setError(''); setModal(item); };
  const submit = async (event) => { event.preventDefault(); setSaving(true); setError(''); try { if (modal[idKey]) await api.put(`${config.path}/${modal[idKey]}`, modal); else await api.post(config.path, modal); setModal(null); load(); } catch (requestError) { setError(errorMessage(requestError)); } finally { setSaving(false); } };
  const remove = async (item) => { if (!window.confirm(`Delete ${config.title.toLowerCase()} record #${item[idKey]}?`)) return; setError(''); try { await api.delete(`${config.path}/${item[idKey]}`); load(); } catch (requestError) { setError(errorMessage(requestError)); } };
  const assign = async (item) => { const mechanicId = window.prompt('Enter the mechanic ID from the Mechanics page.'); if (!mechanicId) return; setSaving(true); try { await api.post(`/bookings/${item.booking_id}/assign-mechanic`, { mechanic_id: mechanicId }); load(); } catch (requestError) { setError(errorMessage(requestError)); } finally { setSaving(false); } };
  const advance = async (item) => { const nextStatus = item.booking_status === 'ASSIGNED' ? 'IN_PROGRESS' : 'COMPLETED'; setSaving(true); try { await api.put(`/bookings/${item.booking_id}/progress`, { booking_status: nextStatus }); load(); } catch (requestError) { setError(errorMessage(requestError)); } finally { setSaving(false); } };
  const display = (item, field) => field === 'customer_id' ? item.customer?.full_name : field === 'vehicle_id' ? item.vehicle?.registration_number : field === 'service_type_id' ? item.service?.service_name : field === 'booking_id' ? `#${item.booking_id}` : item[field];
  return <div className="card table-card"><div className="section-heading"><h3>{config.title}</h3><div className="topbar-actions"><input placeholder={`Search ${config.title.toLowerCase()}`} value={search} onChange={(event) => setSearch(event.target.value)} /><button className="btn btn-outline" onClick={() => setQuery(search)}>Search</button>{role !== 'mechanic' && !(role === 'customer' && ['invoices'].includes(resourceKey)) && <button className="btn btn-primary" onClick={openCreate}>Add</button>}</div></div>{error && <div className="alert error">{error}</div>}<table><thead><tr>{visibleFields.slice(0, 4).map((field) => <th key={field[0]}>{field[1]}</th>)}<th>Actions</th></tr></thead><tbody>{loading ? <tr><td colSpan="6">Loading...</td></tr> : items.length === 0 ? <tr><td colSpan="6">No records found.</td></tr> : items.map((item) => <tr key={item[idKey]}>{visibleFields.slice(0, 4).map((field) => <td key={field[0]}>{display(item, field[0]) || '-'}</td>)}<td>{role === 'admin' && resourceKey === 'bookings' && <button className="btn btn-outline" onClick={() => assign(item)}>Assign</button>} {role === 'mechanic' && resourceKey === 'bookings' && ['ASSIGNED', 'IN_PROGRESS'].includes(item.booking_status) && <button className="btn btn-outline" onClick={() => advance(item)}>{item.booking_status === 'ASSIGNED' ? 'Start' : 'Complete'}</button>} {role !== 'mechanic' && resourceKey !== 'invoices' && !(role === 'customer' && resourceKey === 'invoices') && <><button className="btn btn-outline" onClick={() => openEdit(item)}>Edit</button> <button className="btn btn-danger" onClick={() => remove(item)}>Delete</button></>}</td></tr>)}</tbody></table>{modal && <Modal title={`${modal[idKey] ? 'Edit' : 'Add'} ${config.title}`} fields={visibleFields} values={modal} setValues={setModal} options={options} onSubmit={submit} onClose={() => setModal(null)} saving={saving} error={error} />}</div>;
}

function Dashboard({ role }) { const [stats, setStats] = useState(null); const [error, setError] = useState(''); useEffect(() => { api.get(role === 'admin' ? '/dashboard' : `/${role}/dashboard`).then((response) => setStats(response.data?.data)).catch((requestError) => setError(errorMessage(requestError))); }, [role]); return <><div className="stats-grid">{stats ? Object.entries(stats).map(([key, value]) => <div className="card stat-card stat-primary" key={key}><div className="stat-label">{key.replaceAll('_', ' ')}</div><div className="stat-value">{Number(value).toLocaleString()}</div></div>) : <div className="card table-card">{error || 'Loading dashboard...'}</div>}</div><ResourcePage resourceKey="bookings" role={role} /></>; }

function Shell() { const { auth, logout } = useAuth(); const [page, setPage] = useState('dashboard'); if (auth.role === 'customer') return <CustomerDashboard auth={auth} logout={logout} />; const role = auth.role; const navigation = role === 'admin' ? [['dashboard', 'Dashboard'], ['customers', 'Customers'], ['vehicles', 'Vehicles'], ['services', 'Services'], ['mechanics', 'Mechanics'], ['spare-parts', 'Spare Parts'], ['bookings', 'Bookings'], ['invoices', 'Invoices'], ['payments', 'Payments']] : [['dashboard', 'Dashboard'], ['bookings', 'Assigned Jobs'], ['invoices', 'Invoices']]; const content = page === 'dashboard' ? <Dashboard role={role} /> : <ResourcePage resourceKey={page} role={role} />; return <div className="app-shell"><aside className="sidebar"><div className="brand-block"><h1>VSMS</h1><span>{role.toUpperCase()}</span></div><nav>{navigation.map(([key, label]) => <button key={key} className={page === key ? 'nav-item active' : 'nav-item'} onClick={() => setPage(key)}>{label}</button>)}</nav><button className="btn btn-outline logout-btn" onClick={logout}>Logout</button></aside><main className="main-panel"><header className="topbar"><div><h2>Welcome back, {auth.name || 'User'}</h2><small>Vehicle Service Management Center</small></div><button className="btn btn-outline" onClick={() => setPage('dashboard')}>Dashboard</button></header><div className="content-area">{content}</div></main></div>; }

function LoginPage() { const navigate = useNavigate(); const { login } = useAuth(); const [form, setForm] = useState({ email: '', password: '' }); const [error, setError] = useState(''); const submit = async (event) => { event.preventDefault(); setError(''); try { const response = await api.post('/login', form); const user = response.data.user; login({ ...user, role: user.role.toLowerCase(), token: response.data.token }); navigate(`/${user.role.toLowerCase()}/dashboard`, { replace: true }); } catch (requestError) { setError(errorMessage(requestError)); } }; return <div className="auth-shell"><div className="auth-card"><h2>Vehicle Service Management System</h2>{error && <div className="alert error">{error}</div>}<form onSubmit={submit} className="stack-form"><input placeholder="Email or username" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} required /><input type="password" placeholder="Password" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} required /><button className="btn btn-primary">Login</button></form><button className="btn btn-outline" onClick={() => navigate('/register')}>Create customer account</button></div></div>; }

function RegisterPage() { const navigate = useNavigate(); const { login } = useAuth(); const [form, setForm] = useState({ name: '', email: '', phone: '', password: '', password_confirmation: '' }); const [error, setError] = useState(''); const submit = async (event) => { event.preventDefault(); setError(''); try { const response = await api.post('/register', form); login({ ...response.data.user, token: response.data.token }); navigate('/customer/dashboard', { replace: true }); } catch (requestError) { setError(errorMessage(requestError)); } }; return <div className="auth-shell"><div className="auth-card"><h2>Customer Registration</h2>{error && <div className="alert error">{error}</div>}<form onSubmit={submit} className="stack-form"><input placeholder="Full name" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} required /><input type="email" placeholder="Email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} required /><input placeholder="Phone" value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })} required /><input type="password" placeholder="Password" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} required /><input type="password" placeholder="Confirm password" value={form.password_confirmation} onChange={(event) => setForm({ ...form, password_confirmation: event.target.value })} required /><button className="btn btn-primary">Register</button></form></div></div>; }

function Protected({ role, children }) { const { auth } = useAuth(); if (!auth) return <Navigate to="/login" replace />; if (auth.role !== role) return <Navigate to={`/${auth.role}/dashboard`} replace />; return children; }

export default function AppActions() { return <Routes><Route path="/login" element={<LoginPage />} /><Route path="/register" element={<RegisterPage />} /><Route path="/payment/success" element={<Protected role="customer"><PaymentSuccessPage /></Protected>} /><Route path="/payment/cancel" element={<Protected role="customer"><PaymentCancelPage /></Protected>} /><Route path="/booking-confirmation/:bookingId" element={<Protected role="customer"><BookingConfirmationPage /></Protected>} /><Route path="/admin/dashboard" element={<Protected role="admin"><Shell /></Protected>} /><Route path="/customer/dashboard" element={<Protected role="customer"><Shell /></Protected>} /><Route path="/mechanic/dashboard" element={<Protected role="mechanic"><Shell /></Protected>} /><Route path="*" element={<Navigate to="/login" replace />} /></Routes>; }
